---
title: Projects
listing: 
  - id: dna-stability
    contents: "project_posts/dna_stability/**/index.qmd"
    type: grid
  - id: rna-regulation
    contents: "project_posts/rna_regulation/**/index.qmd"
    type: grid
  - id: disease
    contents: "project_posts/disease/**/index.qmd"
    type: grid
---

## Learning the Molecular Code of RNA Regulation

RNA regulation plays a major role in cellular function, and alterations such as alternative splicing are frequently implicated in human disease including cancer. Key players are RBPs that recognise cis-regulatory RNA sequence elements, such as short sequence motifs or structured RNA folds. However, the position and function of most cis-regulatory elements remain unknown, hindering the interpretation of disease-associated mutations and the resulting splicing changes.

:::{#rna-regulation}
:::

## Regulatory Mechanisms in Human (Patho)Physiology

RNA metabolism is often disturbed in human disease, including neurodegeneration and cancer. In collaboration with molecular biologists and pre-clinical researchers, we examine transcriptome changes under different pathophysiological conditions.

:::{#disease}
:::


## DNA stability

Each use of the DNA template poses a risk to its integrity, leading in the worst case to a complete breakage, known as a DNA double-strand break (DSB). Despite sophisticated repair pathways in the DNA damage response that capture most of these, unrepaired DSBs pose a major threat to genomic integrity and, in the worst cases, can lead to serious diseases such as cancer.  Although most DSBs are induced by exogenous agents such as ionising radiation or chemotherapeutic agents, the impact of endogenous cellular mechanisms should not be underestimated. RNA transcription, DNA replication, the 3D organisation of the genome and their interplay are known to be key factors in determining where and when DSB hotspots occur. However, a holistic view of the endogenous totality of DNA double-strand breaks, the breakome, in human cells has not yet been achieved.

:::{#dna-stability}
:::

