---
title: "Publications"
---
  
Rebekka Bauer, Sofie Patrizia Meyer, Rebecca Raue, Megan A Palmer, Vanesa Maria Guerrero Ruiz, Giulia Cardamone, Silvia Rösser, Milou Heffels, Fabian Roesmann, Alexander Wilhelm, Dieter Lütjohann, Kathi Zarnack, Dominik Christian Fuhrmann, Marek Widera, Tobias Schmid, Bernhard Brüne  
Hypoxia-altered cholesterol homeostasis enhances the expression of interferon-stimulated genes upon SARS-CoV-2 infections in monocytes  
Frontiers in immunology, doi:10.3389/fimmu.2023.1121864, 28 Jun 2023  
https://pubmed.ncbi.nlm.nih.gov/37377965/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Cornelia Rücklé, Nadine Körtel, M Felicia Basilicata, Anke Busch, You Zhou, Peter Hoch-Kraft, Kerstin Tretow, Fridolin Kielisch, Marco Bertin, Mihika Pradhan, Michael Musheev, Susann Schweiger, Christof Niehrs, Oliver Rausch, Kathi Zarnack, Claudia Isabelle Keller Valsecchi, Julian König  
RNA stability controlled by m<sup>6</sup>A methylation contributes to X-to-autosome dosage compensation in mammals  
Nature structural & molecular biology, doi:10.1038/s41594-023-00997-7, 18 May 2023  
https://pubmed.ncbi.nlm.nih.gov/37202476/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Pablo Acera Mateos, You Zhou, Kathi Zarnack, Eduardo Eyras  
Concepts and methods for transcriptome-wide prediction of chemical messenger RNA modifications with machine learning  
Briefings in bioinformatics, doi:10.1093/bib/bbad163, 04 May 2023  
https://pubmed.ncbi.nlm.nih.gov/37139545/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Lena Molitor, Melina Klostermann, Sabrina Bacher, Juliane Merl-Pham, Nadine Spranger, Sandra Burczyk, Carolin Ketteler, Ejona Rusha, Daniel Tews, Anna Pertek, Marcel Proske, Anke Busch, Sarah Reschke, Regina Feederle, Stefanie M Hauck, Helmut Blum, Micha Drukker, Pamela Fischer-Posovszky, Julian König, Kathi Zarnack, Dierk Niessing  
Depletion of the RNA-binding protein PURA triggers changes in posttranscriptional gene regulation and loss of P-bodies  
Nucleic acids research, doi:10.1093/nar/gkac1237, 18 Jan 2023  
https://pubmed.ncbi.nlm.nih.gov/36651277/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Camila de Oliveira Freitas Machado, Michal Schafranek, Mirko Brüggemann, María Clara Hernández Cañás, Mario Keller, Antonella Di Liddo, Andre Brezski, Nicole Blümel, Benjamin Arnold, Anja Bremm, Ilka Wittig, Nicolas Jaé, François McNicoll, Stefanie Dimmeler, Kathi Zarnack, Michaela Müller-McNicoll  
Poison cassette exon splicing of SRSF6 regulates nuclear speckle dispersal and the response to hypoxia  
Nucleic acids research, doi:10.1093/nar/gkac1225, 09 Jan 2023  
https://pubmed.ncbi.nlm.nih.gov/36620874/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Philipp Keil, Alexander Wulf, Nitin Kachariya, Samira Reuscher, Kristin Hühn, Ivan Silbern, Janine Altmüller, Mario Keller, Ralf Stehle, Kathi Zarnack, Michael Sattler, Henning Urlaub, Katja Sträßer  
Npl3 functions in mRNP assembly by recruitment of mRNP components to the transcription site and their transfer onto the mRNA  
Nucleic acids research, doi:10.1093/nar/gkac1206, 30 Dec 2022  
https://pubmed.ncbi.nlm.nih.gov/36583366/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Mariela Cortés-López, Laura Schulz, Mihaela Enculescu, Claudia Paret, Bea Spiekermann, Mathieu Quesnel-Vallières, Manuel Torres-Diz, Sebastian Unic, Anke Busch, Anna Orekhova, Monika Kuban, Mikhail Mesitov, Miriam M Mulorz, Rawan Shraim, Fridolin Kielisch, Jörg Faber, Yoseph Barash, Andrei Thomas-Tikhonenko, Kathi Zarnack, Stefan Legewie, Julian König  
High-throughput mutagenesis identifies mutations and RNA-binding proteins controlling CD19 splicing and CART-19 therapy resistance  
Nature communications, doi:10.1038/s41467-022-31818-y, 22 Sep 2022  
https://pubmed.ncbi.nlm.nih.gov/36138008/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Alisha N Jones, Carina Graß, Isabel Meininger, Arie Geerlof, Melina Klostermann, Kathi Zarnack, Daniel Krappmann, Michael Sattler  
Modulation of pre-mRNA structure by hnRNP proteins regulates alternative splicing of <em>MALT1</em>  
Science advances, doi:10.1126/sciadv.abp9153, 03 Aug 2022  
https://pubmed.ncbi.nlm.nih.gov/35921415/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Rebekka Bauer, Sofie Patrizia Meyer, Karolina Anna Kloss, Vanesa Maria Guerrero Ruiz, Samira Reuscher, You Zhou, Dominik Christian Fuhrmann, Kathi Zarnack, Tobias Schmid, Bernhard Brüne  
Functional RNA Dynamics Are Progressively Governed by RNA Destabilization during the Adaptation to Chronic Hypoxia  
International journal of molecular sciences, doi:10.3390/ijms23105824, 28 May 2022  
https://pubmed.ncbi.nlm.nih.gov/35628634/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Eiman Elwakeel, Mirko Brüggemann, Jessica Wagih, Olga Lityagina, Mohammed A F Elewa, Yingying Han, Timo Frömel, Rüdiger Popp, Adele M Nicolas, Yannick Schreiber, Elise Gradhand, Dominique Thomas, Rolf Nüsing, Julia Steinmetz-Späh, Rajkumar Savai, Emmanouil Fokas, Ingrid Fleming, Florian R Greten, Kathi Zarnack, Bernhard Brüne, Andreas Weigert  
Disruption of Prostaglandin E2 Signaling in Cancer-Associated Fibroblasts Limits Mammary Carcinoma Growth but Promotes Metastasis  
Cancer research, doi:10.1158/0008-5472.CAN-21-2116, 02 Feb 2022  
https://pubmed.ncbi.nlm.nih.gov/35105690/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Ina Koch, Miguel Andrade-Navarro, Marcel H Schulz, Kathi Zarnack  
Bioinformatics in theory and application - highlights of the 36th German Conference on Bioinformatics  
Biological chemistry, doi:10.1515/hsz-2021-0298, 30 Jun 2021  
https://pubmed.ncbi.nlm.nih.gov/34192830/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Laura Schulz, Manuel Torres-Diz, Mariela Cortés-López, Katharina E Hayer, Mukta Asnani, Sarah K Tasian, Yoseph Barash, Elena Sotillo, Kathi Zarnack, Julian König, Andrei Thomas-Tikhonenko  
Direct long-read RNA sequencing identifies a subset of questionable exitrons likely arising from reverse transcription artifacts  
Genome biology, doi:10.1186/s13059-021-02411-1, 29 Jun 2021  
https://pubmed.ncbi.nlm.nih.gov/34183059/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Sebastian de Vries, Vladimir Benes, Isabel S Naarmann-de Vries, Cornelia Rücklé, Katharina Zarnack, Gernot Marx, Dirk H Ostareck, Antje Ostareck-Lederer  
P23 Acts as Functional RBP in the Macrophage Inflammation Response  
Frontiers in molecular biosciences, doi:10.3389/fmolb.2021.625608, 28 Jun 2021  
https://pubmed.ncbi.nlm.nih.gov/34179071/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Nadine Körtel, Cornelia Rücklé, You Zhou, Anke Busch, Peter Hoch-Kraft, F X Reymond Sutandy, Jacob Haase, Mihika Pradhan, Michael Musheev, Dirk Ostareck, Antje Ostareck-Lederer, Christoph Dieterich, Stefan Hüttelmaier, Christof Niehrs, Oliver Rausch, Dan Dominissini, Julian König, Kathi Zarnack  
Deep and accurate detection of m6A RNA modifications using miCLIP2 and m6Aboost machine learning  
Nucleic acids research, doi:10.1093/nar/gkab485, 22 Jun 2021  
https://pubmed.ncbi.nlm.nih.gov/34157120/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Oliver Daniel Schwich, Nicole Blümel, Mario Keller, Marius Wegener, Samarth Thonta Setty, Melinda Elaine Brunstein, Ina Poser, Igor Ruiz De Los Mozos, Beatrix Suess, Christian Münch, François McNicoll, Kathi Zarnack, Michaela Müller-McNicoll  
SRSF3 and SRSF7 modulate 3'UTR length through suppression or activation of proximal polyadenylation sites and regulation of CFIm levels  
Genome biology, doi:10.1186/s13059-021-02298-y, 12 Mar 2021  
https://pubmed.ncbi.nlm.nih.gov/33706811/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Maria Inês Alvelos, Mirko Brüggemann, Fx Reymond Sutandy, Jonàs Juan-Mateu, Maikel Luis Colli, Anke Busch, Miguel Lopes, Ângela Castela, Annemieke Aartsma-Rus, Julian König, Kathi Zarnack, Décio L Eizirik  
The RNA-binding profile of the splicing factor SRSF6 in immortalized human pancreatic β-cells  
Life science alliance, doi:10.26508/lsa.202000825, 30 Dec 2020  
https://pubmed.ncbi.nlm.nih.gov/33376132/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Kathi Zarnack, Sureshkumar Balasubramanian, Michael P Gantier, Vladislav Kunetsky, Michael Kracht, M Lienhard Schmitz, Katja Sträßer  
Dynamic mRNP Remodeling in Response to Internal and External Stimuli  
Biomolecules, doi:10.3390/biom10091310, 16 Sep 2020  
https://pubmed.ncbi.nlm.nih.gov/32932892/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Mihaela Enculescu, Simon Braun, Samarth Thonta Setty, Anke Busch, Kathi Zarnack, Julian König, Stefan Legewie  
Exon Definition Facilitates Reliable Control of Alternative Splicing in the RON Proto-Oncogene  
Biophysical journal, doi:10.1016/j.bpj.2020.02.022, 28 Apr 2020  
https://pubmed.ncbi.nlm.nih.gov/32336349/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Julian König, Kathi Zarnack  
High-throughput approaches in RNA biology  
Methods (San Diego, Calif.), doi:10.1016/j.ymeth.2020.04.002, 12 Apr 2020  
https://pubmed.ncbi.nlm.nih.gov/32278015/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Hyun-Seo Kang, Carolina Sánchez-Rico, Stefanie Ebersberger, F X Reymond Sutandy, Anke Busch, Thomas Welte, Ralf Stehle, Clara Hipp, Laura Schulz, Andreas Buchbender, Kathi Zarnack, Julian König, Michael Sattler  
An autoinhibitory intramolecular interaction proof-reads RNA recognition by the essential splicing factor U2AF2  
Proceedings of the National Academy of Sciences of the United States of America, doi:10.1073/pnas.1913483117, 20 Mar 2020  
https://pubmed.ncbi.nlm.nih.gov/32188783/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Sandra Fischer, Antonella Di Liddo, Katarzyna Taylor, Jamina S Gerhardus, Krzysztof Sobczak, Kathi Zarnack, Julia E Weigand  
Muscleblind-like 2 controls the hypoxia response of cancer cells  
RNA (New York, N.Y.), doi:10.1261/rna.073353.119, 05 Mar 2020  
https://pubmed.ncbi.nlm.nih.gov/32127384/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Elisa Monzón-Casanova, Louise S Matheson, Kristina Tabbada, Kathi Zarnack, Christopher Wj Smith, Martin Turner  
Polypyrimidine tract-binding proteins are essential for B cell development  
eLife, doi:10.7554/eLife.53557, 22 Feb 2020  
https://pubmed.ncbi.nlm.nih.gov/32081131/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Annabelle Dold, Hong Han, Niankun Liu, Andrea Hildebrandt, Mirko Brüggemann, Cornelia Rücklé, Heike Hänel, Anke Busch, Petra Beli, Kathi Zarnack, Julian König, Jean-Yves Roignant, Paul Lasko  
Makorin 1 controls embryonic patterning by alleviating Bruno1-mediated repression of oskar translation  
PLoS genetics, doi:10.1371/journal.pgen.1008581, 25 Jan 2020  
https://pubmed.ncbi.nlm.nih.gov/31978041/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Anke Busch, Mirko Brüggemann, Stefanie Ebersberger, Kathi Zarnack  
iCLIP data analysis: A complete pipeline from sequencing reads to RBP binding sites  
Methods (San Diego, Calif.), doi:10.1016/j.ymeth.2019.11.008, 22 Nov 2019  
https://pubmed.ncbi.nlm.nih.gov/31751605/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Andrea Hildebrandt, Mirko Brüggemann, Cornelia Rücklé, Susan Boerner, Jan B Heidelberger, Anke Busch, Heike Hänel, Andrea Voigt, Martin M Möckel, Stefanie Ebersberger, Anica Scholz, Annabelle Dold, Tobias Schmid, Ingo Ebersberger, Jean-Yves Roignant, Kathi Zarnack, Julian König, Petra Beli  
The RNA-binding ubiquitin ligase MKRN1 functions in ribosome-associated quality control of poly(A) translation  
Genome biology, doi:10.1186/s13059-019-1814-0, 24 Oct 2019  
https://pubmed.ncbi.nlm.nih.gov/31640799/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Antonella Di Liddo, Camila de Oliveira Freitas Machado, Sandra Fischer, Stefanie Ebersberger, Andreas W Heumüller, Julia E Weigand, Michaela Müller-McNicoll, Kathi Zarnack  
A combined computational pipeline to detect circular RNAs in human cancer cells under hypoxic stress  
Journal of molecular cell biology, doi:10.1093/jmcb/mjz094, 28 Sep 2019  
https://pubmed.ncbi.nlm.nih.gov/31560396/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Anica Scholz, Florian Eggenhofer, Rick Gelhausen, Björn Grüning, Kathi Zarnack, Bernhard Brüne, Rolf Backofen, Tobias Schmid  
uORF-Tools-Workflow for the determination of translation-regulatory upstream open reading frames  
PloS one, doi:10.1371/journal.pone.0222459, 13 Sep 2019  
https://pubmed.ncbi.nlm.nih.gov/31513641/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Eiman Elwakeel, Mirko Brüggemann, Annika F Fink, Marcel H Schulz, Tobias Schmid, Rajkumar Savai, Bernhard Brüne, Kathi Zarnack, Andreas Weigert  
Phenotypic Plasticity of Fibroblasts during Mammary Carcinoma Development  
International journal of molecular sciences, doi:10.3390/ijms20184438, 12 Sep 2019  
https://pubmed.ncbi.nlm.nih.gov/31505876/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Lilli Olgeiser, Carl Haag, Susan Boerner, Jernej Ule, Anke Busch, Janine Koepke, Julian König, Michael Feldbrügge, Kathi Zarnack  
The key protein of endosomal mRNP transport Rrm4 binds translational landmark sites of cargo mRNAs  
EMBO reports, doi:10.15252/embr.201846588, 16 Dec 2018  
https://pubmed.ncbi.nlm.nih.gov/30552148/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Julien Béthune, Ralf-Peter Jansen, Michael Feldbrügge, Kathi Zarnack  
Membrane-Associated RNA-Binding Proteins Orchestrate Organelle-Coupled Translation  
Trends in cell biology, doi:10.1016/j.tcb.2018.10.005, 21 Nov 2018  
https://pubmed.ncbi.nlm.nih.gov/30455121/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Simon Braun, Mihaela Enculescu, Samarth T Setty, Mariela Cortés-López, Bernardo P de Almeida, F X Reymond Sutandy, Laura Schulz, Anke Busch, Markus Seiler, Stefanie Ebersberger, Nuno L Barbosa-Morais, Stefan Legewie, Julian König, Kathi Zarnack  
Decoding a cancer-relevant splicing decision in the RON proto-oncogene using high-throughput mutagenesis  
Nature communications, doi:10.1038/s41467-018-05748-7, 19 Aug 2018  
https://pubmed.ncbi.nlm.nih.gov/30120239/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Kathi Zarnack, Michaela Müller-McNicoll  
High-Throughput Screens for cis-Acting RNA Sequence Elements That Promote Nuclear Retention  
Biochemistry, doi:10.1021/acs.biochem.8b00479, 25 May 2018  
https://pubmed.ncbi.nlm.nih.gov/29792686/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
F X Reymond Sutandy, Stefanie Ebersberger, Lu Huang, Anke Busch, Maximilian Bach, Hyun-Seo Kang, Jörg Fallmann, Daniel Maticzka, Rolf Backofen, Peter F Stadler, Kathi Zarnack, Michael Sattler, Stefan Legewie, Julian König  
In vitro iCLIP-based modeling uncovers how the splicing factor U2AF2 relies on regulation by cofactors  
Genome research, doi:10.1101/gr.229757.117, 13 Apr 2018  
https://pubmed.ncbi.nlm.nih.gov/29643205/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Andrea Hildebrandt, Gregorio Alanis-Lobato, Andrea Voigt, Kathi Zarnack, Miguel A Andrade-Navarro, Petra Beli, Julian König  
Interaction profiling of RNA-binding ubiquitin ligases reveals a link between posttranscriptional regulation and the ubiquitin system  
Scientific reports, doi:10.1038/s41598-017-16695-6, 30 Nov 2017  
https://pubmed.ncbi.nlm.nih.gov/29185492/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Nejc Haberman, Ina Huppertz, Jan Attig, Julian König, Zhen Wang, Christian Hauer, Matthias W Hentze, Andreas E Kulozik, Hervé Le Hir, Tomaž Curk, Christopher R Sibley, Kathi Zarnack, Jernej Ule  
Erratum to: Insights into the design and interpretation of iCLIP experiments  
Genome biology, doi:10.1186/s13059-017-1294-z, 17 Aug 2017  
https://pubmed.ncbi.nlm.nih.gov/28810898/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Valentina Botti, François McNicoll, Michaela C Steiner, Florian M Richter, Anfisa Solovyeva, Marius Wegener, Oliver D Schwich, Ina Poser, Kathi Zarnack, Ilka Wittig, Karla M Neugebauer, Michaela Müller-McNicoll  
Cellular differentiation state modulates the mRNA export activity of SR proteins  
The Journal of cell biology, doi:10.1083/jcb.201610051, 09 Jun 2017  
https://pubmed.ncbi.nlm.nih.gov/28592444/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Sameer Dixit, Michaela Müller-McNicoll, Vojtěch David, Kathi Zarnack, Jernej Ule, Hassan Hashimi, Julius Lukeš  
Differential Binding of Mitochondrial Transcripts by MRB8170 and MRB4160 Regulates Distinct Editing Fates of Mitochondrial mRNA in Trypanosomes  
mBio, doi:10.1128/mBio.02288-16, 02 Feb 2017  
https://pubmed.ncbi.nlm.nih.gov/28143982/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Nejc Haberman, Ina Huppertz, Jan Attig, Julian König, Zhen Wang, Christian Hauer, Matthias W Hentze, Andreas E Kulozik, Hervé Le Hir, Tomaž Curk, Christopher R Sibley, Kathi Zarnack, Jernej Ule  
Insights into the design and interpretation of iCLIP experiments  
Genome biology, doi:10.1186/s13059-016-1130-x, 18 Jan 2017  
https://pubmed.ncbi.nlm.nih.gov/28093074/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Jan Attig, Igor Ruiz de Los Mozos, Nejc Haberman, Zhen Wang, Warren Emmett, Kathi Zarnack, Julian König, Jernej Ule  
Splicing repression allows the gradual emergence of new Alu-exons in primate evolution  
eLife, doi:10.7554/eLife.19545, 19 Nov 2016  
https://pubmed.ncbi.nlm.nih.gov/27861119/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Michaela Müller-McNicoll, Valentina Botti, Antonio M de Jesus Domingues, Holger Brandl, Oliver D Schwich, Michaela C Steiner, Tomaz Curk, Ina Poser, Kathi Zarnack, Karla M Neugebauer  
SR proteins are NXF1 adaptors that link alternative RNA processing to mRNA export  
Genes & development, doi:10.1101/gad.276477.115, 06 Mar 2016  
https://pubmed.ncbi.nlm.nih.gov/26944680/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Jernej Murn, Marianna Teplova, Kathi Zarnack, Yang Shi, Dinshaw J Patel  
Recognition of distinct RNA motifs by the clustered CCCH zinc fingers of neuronal protein Unkempt  
Nature structural & molecular biology, doi:10.1038/nsmb.3140, 08 Dec 2015  
https://pubmed.ncbi.nlm.nih.gov/26641712/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Mojca Tajnik, Alessandra Vigilante, Simon Braun, Heike Hänel, Nicholas M Luscombe, Jernej Ule, Kathi Zarnack, Julian König  
Intergenic Alu exonisation facilitates the evolution of tissue-specific transcript ends  
Nucleic acids research, doi:10.1093/nar/gkv956, 25 Sep 2015  
https://pubmed.ncbi.nlm.nih.gov/26400176/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Jernej Murn, Kathi Zarnack, Yawei J Yang, Omer Durak, Elisabeth A Murphy, Sihem Cheloufi, Dilenny M Gonzalez, Marianna Teplova, Tomaž Curk, Johannes Zuber, Dinshaw J Patel, Jernej Ule, Nicholas M Luscombe, Li-Huei Tsai, Christopher A Walsh, Yang Shi  
Control of a neuronal morphology program by an RNA-binding zinc finger protein, Unkempt  
Genes & development, doi:10.1101/gad.258483.115, 05 Mar 2015  
https://pubmed.ncbi.nlm.nih.gov/25737280/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Manuel D Diaz-Muñoz, Sarah E Bell, Kirsten Fairfax, Elisa Monzon-Casanova, Adam F Cunningham, Mar Gonzalez-Porta, Simon R Andrews, Victoria I Bunik, Kathi Zarnack, Tomaž Curk, Ward A Heggermont, Stephane Heymans, Gary E Gibson, Dimitris L Kontoyiannis, Jernej Ule, Martin Turner  
The RNA-binding protein HuR is essential for the B cell antibody response  
Nature immunology, doi:10.1038/ni.3115, 24 Feb 2015  
https://pubmed.ncbi.nlm.nih.gov/25706746/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Kathi Zarnack, Julian König, Mojca Tajnik, Iñigo Martincorena, Sebastian Eustermann, Isabelle Stévant, Alejandro Reyes, Simon Anders, Nicholas M Luscombe, Jernej Ule  
Direct competition between hnRNP C and U2AF65 protects the transcriptome from the exonization of Alu elements  
Cell, doi:10.1016/j.cell.2012.12.023, 05 Feb 2013  
https://pubmed.ncbi.nlm.nih.gov/23374342/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Julian König, Kathi Zarnack, Nicholas M Luscombe, Jernej Ule  
Protein-RNA interactions: new genomic technologies and perspectives  
Nature reviews. Genetics, doi:10.1038/nrg3141, 19 Jan 2012  
https://pubmed.ncbi.nlm.nih.gov/22251872/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
James R Tollervey, Zhen Wang, Tibor Hortobágyi, Joshua T Witten, Kathi Zarnack, Melis Kayikci, Tyson A Clark, Anthony C Schweitzer, Gregor Rot, Tomaž Curk, Blaž Zupan, Boris Rogelj, Christopher E Shaw, Jernej Ule  
Analysis of alternative splicing associated with aging and neurodegeneration in the human brain  
Genome research, doi:10.1101/gr.122226.111, 18 Aug 2011  
https://pubmed.ncbi.nlm.nih.gov/21846794/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Janine Koepke, Florian Kaffarnik, Carl Haag, Kathi Zarnack, Nicholas M Luscombe, Julian König, Jernej Ule, Ronny Kellner, Dominik Begerow, Michael Feldbrügge  
The RNA-binding protein Rrm4 is essential for efficient secretion of endochitinase Cts1  
Molecular & cellular proteomics : MCP, doi:10.1074/mcp.M111.011213, 03 Aug 2011  
https://pubmed.ncbi.nlm.nih.gov/21808052/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Julian Konig, Kathi Zarnack, Gregor Rot, Tomaz Curk, Melis Kayikci, Blaz Zupan, Daniel J Turner, Nicholas M Luscombe, Jernej Ule  
iCLIP--transcriptome-wide mapping of protein-RNA interactions with individual nucleotide resolution  
Journal of visualized experiments : JoVE, doi:10.3791/2638, 12 May 2011  
https://pubmed.ncbi.nlm.nih.gov/21559008/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Zhen Wang, Melis Kayikci, Michael Briese, Kathi Zarnack, Nicholas M Luscombe, Gregor Rot, Blaž Zupan, Tomaž Curk, Jernej Ule  
iCLIP predicts the dual splicing effects of TIA-RNA interactions  
PLoS biology, doi:10.1371/journal.pbio.1000530, 05 Nov 2010  
https://pubmed.ncbi.nlm.nih.gov/21048981/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Julian König, Kathi Zarnack, Gregor Rot, Tomaz Curk, Melis Kayikci, Blaz Zupan, Daniel J Turner, Nicholas M Luscombe, Jernej Ule  
iCLIP reveals the function of hnRNP particles in splicing at individual nucleotide resolution  
Nature structural & molecular biology, doi:10.1038/nsmb.1838, 06 Jul 2010  
https://pubmed.ncbi.nlm.nih.gov/20601959/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Kathi Zarnack, Michael Feldbrügge  
Microtubule-dependent mRNA transport in fungi  
Eukaryotic cell, doi:10.1128/EC.00030-10, 18 May 2010  
https://pubmed.ncbi.nlm.nih.gov/20472693/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Evelyn Vollmeister, Carl Haag, Kathi Zarnack, Sebastian Baumann, Julian König, Gertrud Mannhaupt, Michael Feldbrügge  
Tandem KH domains of Khd4 recognize AUACCC and are essential for regulation of morphology as well as pathogenicity in Ustilago maydis  
RNA (New York, N.Y.), doi:10.1261/rna.1817609, 27 Oct 2009  
https://pubmed.ncbi.nlm.nih.gov/19854870/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Julian König, Sebastian Baumann, Janine Koepke, Thomas Pohlmann, Kathi Zarnack, Michael Feldbrügge  
The fungal RNA-binding protein Rrm4 mediates long-distance transport of ubi1 and rho3 mRNAs  
The EMBO journal, doi:10.1038/emboj.2009.145, 05 Jun 2009  
https://pubmed.ncbi.nlm.nih.gov/19494833/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Kathi Zarnack, Heiko Eichhorn, Regine Kahmann, Michael Feldbrügge  
Pheromone-regulated target genes respond differentially to MAPK phosphorylation of transcription factor Prf1  
Molecular microbiology, doi:10.1111/j.1365-2958.2008.06345.x, 17 Jul 2008  
https://pubmed.ncbi.nlm.nih.gov/18627457/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Michael Feldbrügge, Kathi Zarnack, Evelyn Vollmeister, Sebastian Baumann, Janine Koepke, Julian König, Martin Münsterkötter, Gertrud Mannhaupt  
The posttranscriptional machinery of Ustilago maydis  
Fungal genetics and biology : FG & B, doi:10.1016/j.fgb.2008.03.013, 13 May 2008  
https://pubmed.ncbi.nlm.nih.gov/18468465/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Kathi Zarnack, Michael Feldbrügge  
mRNA trafficking in fungi  
Molecular genetics and genomics : MGG, doi:10.1007/s00438-007-0271-8, 05 Sep 2007  
https://pubmed.ncbi.nlm.nih.gov/17768642/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
  
Kathi Zarnack, Sebastian Maurer, Florian Kaffarnik, Oliver Ladendorf, Andreas Brachmann, Jörg Kämper, Michael Feldbrügge  
Tetracycline-regulated gene expression in the pathogen Ustilago maydis  
Fungal genetics and biology : FG & B, doi:10.1016/j.fgb.2006.05.006, 18 Jul 2006  
https://pubmed.ncbi.nlm.nih.gov/16843015/?utm_source=Other&utm_medium=rss&utm_campaign=pubmed-2&utm_content=1jue2dFuI_LFj_phV9s9PjTEhPInBPr1NTb858Yzvn1De2GMXv&fc=20230630074326&ff=20230705040716&v=2.17.9.post6+86293ac  
